[[sinewave]]
arch = "i686"
git-tree-sha1 = "94aac6926eb444722c5e0af0edbdc2a089b27db9"
os = "windows"

    [[sinewave.download]]
    sha256 = "2913f7fc556536594ea8042e43b209f802f12994171f625641ccabf60543900a"
    url = "https://github.com/jakubwro/sinewave_jll/releases/download/sinewave-v0.3.0+0/sinewave.v0.3.0.i686-w64-mingw32.tar.gz"
[[sinewave]]
arch = "x86_64"
git-tree-sha1 = "a2a8154e1dd5891e6f6f5cdf852e670f1b22bc35"
libc = "glibc"
os = "linux"

    [[sinewave.download]]
    sha256 = "3773bb60392f92a5a7347f08f3865a26370c5f1eb7bd3a7472fe6814a820c09d"
    url = "https://github.com/jakubwro/sinewave_jll/releases/download/sinewave-v0.3.0+0/sinewave.v0.3.0.x86_64-linux-gnu.tar.gz"
[[sinewave]]
arch = "i686"
git-tree-sha1 = "a5a447be811ada79de1bb542cdb01ba25d9b9d12"
libc = "musl"
os = "linux"

    [[sinewave.download]]
    sha256 = "e0dad74a2b0810af98b907c556405449217ba8d1d65bdc940a49972c6b620c20"
    url = "https://github.com/jakubwro/sinewave_jll/releases/download/sinewave-v0.3.0+0/sinewave.v0.3.0.i686-linux-musl.tar.gz"
[[sinewave]]
arch = "x86_64"
git-tree-sha1 = "2f0bca9727e72a187e9ce1a77744eb8f444ed951"
libc = "musl"
os = "linux"

    [[sinewave.download]]
    sha256 = "1e76b9b05193068c3ab0ec8da43ff9fcd4340b60360e1dab0c39c84cd9fa3e16"
    url = "https://github.com/jakubwro/sinewave_jll/releases/download/sinewave-v0.3.0+0/sinewave.v0.3.0.x86_64-linux-musl.tar.gz"
[[sinewave]]
arch = "i686"
git-tree-sha1 = "f8377fa9507728e4995e3e92acabb43b8f91ce08"
libc = "glibc"
os = "linux"

    [[sinewave.download]]
    sha256 = "51df838a2070552b88eb9a8ea9268fca2816be7370310d947e302118ecc8999a"
    url = "https://github.com/jakubwro/sinewave_jll/releases/download/sinewave-v0.3.0+0/sinewave.v0.3.0.i686-linux-gnu.tar.gz"
[[sinewave]]
arch = "aarch64"
git-tree-sha1 = "09db65b575efd1c4ff8962202323634f1fed5008"
libc = "musl"
os = "linux"

    [[sinewave.download]]
    sha256 = "3b7e167d9b662d9e4f981dfea2ad176c884914126ce63e85451592898bbbcac3"
    url = "https://github.com/jakubwro/sinewave_jll/releases/download/sinewave-v0.3.0+0/sinewave.v0.3.0.aarch64-linux-musl.tar.gz"
[[sinewave]]
arch = "powerpc64le"
git-tree-sha1 = "d5ecb0c62fe5c7a90dca0e562cc6fcbb5dba8aaa"
libc = "glibc"
os = "linux"

    [[sinewave.download]]
    sha256 = "0146e2c4392c423e2afade184c3806feac96a648b553c53a9cf0757a99f1caae"
    url = "https://github.com/jakubwro/sinewave_jll/releases/download/sinewave-v0.3.0+0/sinewave.v0.3.0.powerpc64le-linux-gnu.tar.gz"
[[sinewave]]
arch = "x86_64"
git-tree-sha1 = "fca5c767da623a197a43a0d79ad70dfe355bdb25"
os = "macos"

    [[sinewave.download]]
    sha256 = "657a0486071aa813c3da795ca8e7d0a6aff5ac95683a65d7c2ab5d0cfce93114"
    url = "https://github.com/jakubwro/sinewave_jll/releases/download/sinewave-v0.3.0+0/sinewave.v0.3.0.x86_64-apple-darwin14.tar.gz"
[[sinewave]]
arch = "aarch64"
git-tree-sha1 = "19b76086a5332e90a9da65a091ecd09f144bcc84"
libc = "glibc"
os = "linux"

    [[sinewave.download]]
    sha256 = "cea1bbc2c55e2773df4b77a10935f85314c1db22327eb4e0dd8e14423d84346a"
    url = "https://github.com/jakubwro/sinewave_jll/releases/download/sinewave-v0.3.0+0/sinewave.v0.3.0.aarch64-linux-gnu.tar.gz"
[[sinewave]]
arch = "x86_64"
git-tree-sha1 = "fdd98ab0775ae229b6414a3a511c1b0259009aa1"
os = "freebsd"

    [[sinewave.download]]
    sha256 = "0714ae9b51aa9301151a0e4e6de26c40f8a340e9637660c3b9d29864b4a37a47"
    url = "https://github.com/jakubwro/sinewave_jll/releases/download/sinewave-v0.3.0+0/sinewave.v0.3.0.x86_64-unknown-freebsd11.1.tar.gz"
[[sinewave]]
arch = "armv7l"
git-tree-sha1 = "c975f46a227e376424ec278441f058ebcb2c7353"
libc = "musl"
os = "linux"

    [[sinewave.download]]
    sha256 = "f5ba4b08b3e86e331c97d947b07f385e883f2e931b8e3aa61e9c0d3a8022b33a"
    url = "https://github.com/jakubwro/sinewave_jll/releases/download/sinewave-v0.3.0+0/sinewave.v0.3.0.arm-linux-musleabihf.tar.gz"
[[sinewave]]
arch = "armv7l"
git-tree-sha1 = "7e7fd7d08d3ede8e5f0c4b7822e7c82f44b281a2"
libc = "glibc"
os = "linux"

    [[sinewave.download]]
    sha256 = "c25cd96146b03b40e584df89f1569116c581410f3f7d67fbb203db7bac6950fb"
    url = "https://github.com/jakubwro/sinewave_jll/releases/download/sinewave-v0.3.0+0/sinewave.v0.3.0.arm-linux-gnueabihf.tar.gz"
[[sinewave]]
arch = "x86_64"
git-tree-sha1 = "e1d0df63d122c66dae8009371a4a39aa9a4bdf8f"
os = "windows"

    [[sinewave.download]]
    sha256 = "48ff66aea5c282d14aaba8925d5fb2eef8d6316c918b4533d215b0eacd3ed9da"
    url = "https://github.com/jakubwro/sinewave_jll/releases/download/sinewave-v0.3.0+0/sinewave.v0.3.0.x86_64-w64-mingw32.tar.gz"
